destination: ./_site
safe: true
lsi: false
port: 4000
permalink: /news/:categories/:year/:month/:day/:title/
title: LameStation

name: LameStation News
description: The latest news at LameStation headquarters
url: https://www.lamestation.com

pages_list:
  Setup:
    - "/setup/"
  Build:
    - "/build/"
  Code:
    - "/code/"
  Games:
    - "/games/"
  Reference:
    - "/reference/"
  About:
    - News: "/news/"
    - Contact: "/contact/"

collections:
  games:
    output: true
    permalink: /games/:path/
  library:
    output: true
    permalink: /reference/library/:path/
